name = "clang-format"
type = "cli"

[platform]
download-file = "clang-format-{version}_{os}-{arch}"
checksum-file = "clang-format-{version}_{os}-{arch}.sha512sum"

[install]
checksum-url = "https://github.com/davidwinter/static-clang-tools-binaries/releases/download/v{version}/{checksum_file}"
download-url = "https://github.com/davidwinter/static-clang-tools-binaries/releases/download/v{version}/{download_file}"

[resolve]
git-url = "https://github.com/davidwinter/static-clang-tools-binaries"
