name = "clang-apply-replacements"
type = "cli"

[platform.linux]
archs = [ "x86_64" ]
download-file = "clang-apply-replacements-{version}_{os}-{arch}"
# checksum-file = "clang-apply-replacements-{version}_{os}-{arch}.sha512sum"

[platform.macos]
archs = [ "x86_64", "aarch64" ]
download-file = "clang-apply-replacements-{version}_{os}-{arch}"
# checksum-file = "clang-apply-replacements-{version}_{os}-{arch}.sha512sum"

[platform.windows]
archs = [ "x86_64" ]
download-file = "clang-apply-replacements-{version}_{os}-{arch}.exe"
# checksum-file = "clang-apply-replacements-{version}_{os}-{arch}.sha512sum"

[install]
# checksum-url = "https://github.com/davidwinter/static-clang-tools-binaries/releases/download/v{version}/{checksum_file}"
download-url = "https://github.com/davidwinter/static-clang-tools-binaries/releases/download/v{version}/{download_file}"

[resolve]
git-url = "https://github.com/davidwinter/static-clang-tools-binaries"
